"""Add comment to reviews

Revision ID: 55f768e0c85c
Revises: 33b3de0da506
Create Date: 2024-01-11 15:53:07.157255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f768e0c85c'
down_revision = '33b3de0da506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'comment')
    # ### end Alembic commands ###
